### ISSUE TITLE
Gives error when running the example code

### ISSUE THREAD

**Issue by h0rb** [JoshMerlino/namemc#1]
hello, 
I get this error when I run example code:
`const users = await  lookupName("tehpicix");
              ^^^^^

SyntaxError: await is only valid in async function
`

**Comment by GaboTheCoder** [comment]
That's not a package issue, The error is in the message, use a async function.

**Comment by JoshMerlino** [comment]
Because the functions return promises, I find it more elegant to use async/await - assuming it is in an async function.

You can fix this by wrapping it in:

```JavaScript
(async function(){
    // await ...
}())
```
