### ISSUE TITLE
Past Names

### ISSUE THREAD

**Issue by ToeDev** [JoshMerlino/namemc#29]
"Past Names" don't seem to be providing any info. They all show as "null"

**Comment by JoshMerlino** [comment]
Have you determined if this is specific to one user or consistent with every name you query? Also can you send a snippet of your source?

**Comment by ToeDev** [comment]
All names I've tried return no "current name" or "past names".  I haven't even gotten as far as integrating this into my code. It display no past names just in a web browser :/.

Here is an example query I did [https://joshm.us.to/api/namemc/v1/lookup?query=deputy_donut]

And here is the output.
[https://pastebin.com/2TgHiDdt]

**Comment by JoshMerlino** [comment]
It looks like NameMC changed their HTML again 😠, Ill try and patch this tonight.

**Comment by JoshMerlino** [comment]
Fixed in #32
