### ISSUE TITLE
"Require"

### ISSUE THREAD

**Issue by AndyReckt** [JoshMerlino/namemc#3]
hi, in ur readme you say we can also import using the "require" function, i would like to know whats the command line, since the "import" one doesnt work for me

**Comment by Varmolord** [comment]
Same for me.. **const lookupName = require('namemc')** does not work.

**Comment by JoshMerlino** [comment]
The package returns an object with the functions your looking for. You can use the destructure syntax to destructure the methods you need. 

For example:
```javascript
const { lookupName } = require("namemc");
// Or
const lookupName = require("namemc").lookupName;
```

The same will work with the other functions in the package
