### ISSUE TITLE
Cloudflare rejected

### ISSUE THREAD

**Issue by Villhahallon** [JoshMerlino/namemc#45]
Hello, Got this error while running a command to use this package.
It worked perfectly then just stopped.

anyone else who got this?

Error: Cloudflare has rejected the request. Ray ID: ********

**Comment by JoshMerlino** [comment]
Unfortunately, NameMC has cloudflare ddos protection which sometimes gets in the way of the web scraping engine. There's nothing I can do to fix this, however one thing that seems to work is just opening namemc in the browser and solving the captia if it gives one.
